### ISSUE TITLE
Unhandled 'error' event on Windows 10 and 8

### ISSUE THREAD

**Issue by sindregusdal** [yarnjs/yarn#37] opened 2016-08-14 08:57 UTC
Tried on 2 computers (Win 10 and Win 8), to init a yarn project. Get same error both times:

events.js:154
    throw er; //unhandled 'error' event
    ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:856:11)
    ............

Would love to give Yarn a try, as it sounds pretty awesome.

**Comment by hswolff** [comment] 2016-08-17 12:04
What command are you running that it throws that error? `yarn init`? Mind throwing a screen cap of your terminal window so I can just see it in full?

Definitely interested in debugging this - thanks so much for the error report!

**Comment by sindregusdal** [comment] 2016-08-23 11:35
Sorry. I was late to reply. Here it is.

![yarn-fail](https://cloud.githubusercontent.com/assets/996622/17890456/6d689c1a-6936-11e6-88ea-cf842afa70b9.jpg)

**Comment by bmcminn** [comment] 2016-08-27 08:44
Same issue on Win7 Pro 64bit, Node: 6.0.0

**Comment by hswolff** [comment] 2016-08-27 21:46
Thank you @sindregusdal and @bmcminn for the feedback!

I think the issue is https://github.com/nodejs/node-v0.x-archive/issues/2318 . I'm looking to fix this by using https://www.npmjs.com/package/cross-spawn

Going to try that out and push a new version as soon as I can!

**Comment by hswolff** [comment] 2016-08-30 03:41
Just published version `1.2.0` to fix this. If you re-install `npm install -g yarn-cli` it should install the new yarn version with the hopeful fix!

**Comment by sindregusdal** [comment] 2016-08-30 07:34
Great. Will test the install asap.

**Comment by bmcminn** [comment] 2016-09-01 05:17
So it seems that `yarn init` is working now, however I have no idea what the generated filesystem is supposed to look like after it completes, but it seems sparse...

    +-- /test-yarn
      +-- /_posts
      |  `-- my-first-post.md
      +-- /_site
      |  `-- /images
      |    `-- ...empty folder
      +-- /images
      |  `-- ...empty folder
      +-- _config.yml
      +-- about.md
      \-- package.json

Also, the `package.json` file seems really incomplete, and I don't believe it should be autogenerated, I think leaving it alone and letting the developer use `npm init` would be a sufficient option.

```// generated package.json
{"main":"my-yarn-site","dependencies":{"yarn-excerpt":"^0.7.0","yarn-html-minifier":"^0.6.0","yarn-theme-thread":"^0.3.0"}}
```

But running `yarn build` after `yarn init` hits an error where LESS can't find `layout.less`, even though it's present in the `thread` theme installed during `yarn init`.

If any of the above look like a separate issue(s), let me know and I'll setup another more issues to track these better.

**Comment by AndrewStaroscik** [comment] 2016-09-21 13:18
Just installed yarn v1.2.0 and am getting the same error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/yarn-cli/node_modules/yarnjs/node_modules/.bin/http-server ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

**Comment by hswolff** [comment] 2016-09-21 14:04
@AndrewStaroscik can you provide what node and npm version you're using?

Testing on Windows is harder for me but I'm surprised to hear there's issues on OS X. Will look into it asap.

**Comment by AndrewStaroscik** [comment] 2016-09-21 18:44
Node v 6.6.0
npm v 3.10.3

**Comment by hswolff** [comment] 2016-09-25 21:01
@AndrewStaroscik just published `1.3.0` to fix your issue. I think just an `npm install -g yarn-cli` will update the version, but I'm not sure. Might have to uninstall first `npm uninstall -g yarn-cli` and then re-install.

@bmcminn your issue seems to be related to how less is resolving module paths, as they're different on windows. That's a harder nut to crack but I'm working on it.

**Comment by hswolff** [comment] 2016-09-26 01:39
@sindregusdal and @bmcminn I just published `1.4.0` which I believe fixes yarn compatibility for Windows!

Thanks **so** much for opening this issue to alert me to this issue!

Closing this issue as I believe it is now resolved! Yay!

**Comment by hswolff** [comment] 2016-09-26 01:39
(relevant commit https://github.com/yarnjs/yarn/commit/445ef6b33f086c40ed101dbc97a2491124856196)

**Closed by hswolff** 2016-09-26 01:39 UTC

**Comment by AndrewStaroscik** [comment] 2016-09-26 12:12
@hswolff install is working for me on Mac osx with Yarn v 1.4.0.

**Comment by bmcminn** [comment] 2016-09-26 14:18
Works a treat on Windows now :)
